name: Minecraft_Test
version: '${project.version}'
main: mctest.minecraft_test.Minecraft_Test
api-version: '1.19'
commands:
  menu:
    description: Opens the Server Menu
    usage: /menu
    aliases: m
    permission: infected.menu
    permission-message: You do not have permission to open the menu
  setSpawn:
    description: Sets the spawn
    usage: /setSpawn
    permission: spawn.set
  spawn:
    description: Teleports you to spawn
    usage: /spawn
    permission: spawn.teleport
  loadout:
    description: Loadout editor commands.
    usage: /loadout
    aliases: lo
    permission: infected.loadout
    permission-message: You do not have permission to run this command