#Configure which scores should be tracked. More info on the wiki (https://s-and-r.gitbook.io/infected-mc/) or discord (https://discord.gg/jvvftFJdzD)

# Games won as survivor
survivor-games-won: true

# Games won as infected
infected-games-won: true

# Kills made as survivor
survivor-kills: true

# Kills made as infected
infected-kills: true

# Number of infected games played
games-played: true

# Number of players listed in the leaderboards
leaderboard-amount: 3
