#Main settings
wait-timer: 5

respawn-timer: 5

match-length: 10

max-players: 2

min-players: 1

num-starting-infected: 1

lobby-worlds:
  - world #this is an example

queue-start-broadcast-enabled: TRUE

allowed-worlds:
  - world #this is an example

default-spawn:
  world: placeholder
  x: placeholder
  y: placeholder
  z: placeholder
  pitch: placeholder
  yaw: placeholder