#Main settings for more help please visit the wiki () or join the discord ()

### Match settings ###
# Queue length in seconds
wait-timer: 5

# Respawn timer for infected in seconds
respawn-timer: 3

# Delay before match starts for people to choose classes.
# Players will be unable to move during this time.
match-delay: 10

# Game length in seconds
match-length: 45

# Maximum amount of players for a game
max-players: 2

# Minimum amount of players needed to begin a countdown for a game
min-players: 1

# Number of starting infected
num-starting-infected: 1

#Time before teleporting players back to the lobby after a game ends
end-time: 3

## Reward settings (must have vault and economy handler for money to apply) ##
# Rewards for each team member when the team wins
currency-symbol: "$"

##Should prices be enabled for loadouts (Requires vault)##
loadout-prices: false

#Should a broadcast be sent to lobbies when a queue starts
queue-start-broadcast-enabled: true

#Should scores be tracked
keep-score: true

# If enabled you can set a specific permission for each loadout if you want them to be seen with certain permissions and
# not just type.
# If set to true but no permission is set, it will default to the type
# The permission will always be set to "infected.loadout.[Your custom permission node]"
# For this example loadout:
#   loadout:
#     placeholder: placeholder
#     description: placeholder
#     permission: test
# The permission node will be: infected.loadout.test
use-custom-loadout-perms: false

# IF enabled, number of starting infected will scale based on the number of players
# This will only work if the ratio is less than or equal to the number of people playing
# Otherwise it will default to num-starting-infected
use-scaling-infected: false

# Ratio of starting infected to survivors
infected-ratio: 1-10 # This means 1 infected for every 10 players, must use "-" to separate numbers
ratio-rounds-up: false # If enabled, the plugin will round up for number of starting infected

# Worlds that can get an announcement on the beginning of a queue if
# queue-start-broadcast-enabled is true.
lobby-worlds:
  - world #this is an example

# Worlds where a match can be held
allowed-worlds:
  - world #this is an example

# Default spawn for those not playing/without an infected/survivor role
default-spawns:
  exampleworld: # World names must be in lower case!
    firstexample:
      x: 0
      y: 0
      z: 0
      pitch: 0
      yaw: 0
    secondexample:
      x: 0
      y: 0
      z: 0
      pitch: 0
      yaw: 0