name: Minecraft_Test
version: '${project.version}'
main: mctest.minecraft_test.Minecraft_Test
api-version: '1.19'
authors: [DeathsValentine, Mithraea]
Prefix: Infected

commands:
  menu:
    description: Opens the Server Menu
    usage: /menu
    aliases: [m, im]
    permission: infected.menu
    permission-message: You do not have permission to open the menu
  setSpawn: #remove this
    description: Sets the spawn
    usage: /setSpawn
    permission: spawn.set
  spawn:
    description: Teleports you to spawn
    usage: /ispawn
    aliases: is
    permission: infected.spawn
    permission-message: You do not have permission to run this command
  loadout:
    description: Loadout editor commands.
    usage: /loadout
    aliases: [lo, ilo]
    permission: infected.loadout
    permission-message: You do not have permission to run this command
  reload:
    description: Reload config
    usage: /infectedreload
    aliases: ir
    permission: infected.reload
    permission-message: You do not have permission to run this command
  infected:
    description: Basic plugin commands
    usage: /infected
    aliases: in
    permission: infected
    permission-message: You do not have permission to run this command